Prelude_v2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs
  resources :bands

  root 'songs#index'

end

Prelude_v2/app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :songs
  has_many :users
end

Prelude_v2/app/models/song.rb
class Song < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :artist, presence: true

  mount_uploader :chart, ::ChartUploader
  mount_uploader :mp3, ::Mp3Uploader

  # songs belong to bands
  belongs_to :band
end

Prelude_v2/app/models/user.rb
class User < ActiveRecord::Base
  # users belong to bands
  belongs_to :band

  after_create :create_invalid_band
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def create_invalid_band
    b = Band.new({name: nil})
    #saves band without running validations
    b.save(validate: false)

    self.update_attribute(:band_id, b.id)
    #self.band_id = -1
  end

end

Prelude_v2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  respond_to :html

  before_filter :ensure_valid_band, only: :index

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  def ensure_valid_band
    if current_user && !(current_user.band.valid?)
    #if current_user && current_user.band_id == -1
      redirect_to (edit_band_path(current_user.band.id))
      return
    end
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :username
    end


end

Prelude_v2/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
    @band = Band.find(params[:id])
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
    @band = Band.find(params[:id])
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      @band = Band.find(params[:id])
      if @band.update_attributes(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name)
    end
end

Prelude_v2/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_song, only: [:show, :edit, :update, :destroy]
  #before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]


  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      @song = Song.find(params[:id])
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist, :band_id, :chart, :mp3)
    end

end

Prelude_v2/app/helpers/application_helper.rb
module ApplicationHelper
end

Prelude_v2/app/helpers/bands_helper.rb
module BandsHelper
end

Prelude_v2/app/helpers/songs_helper.rb
module SongsHelper
end

Prelude_v2/app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Prelude_v2/app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

Prelude_v2/app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

Prelude_v2/app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

Prelude_v2/app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

Prelude_v2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PreludeV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<% if user_signed_in? %>
  <body class = "nonadmin-home">
<% else %>
  <body>
<% end %>

<!-- Navbar -->
<nav>
  <div class = "container">

      <!-- Prelude logo -->
      <div class="navbar-header">
        <h4>
          <%= link_to image_tag("Prelude-logo3.png"), songs_path %>
        </h4>
      </div>

      <div>
        <ul class="nav navbar navbar-right">
          <% if user_signed_in? %>
            <li class = "button">
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          </ul>
          <ul class="nav navbar navbar-right">
            <li class = "button">
                <%= link_to('Home', root_path) %>
            </li>
          </ul>

          <% else %>
            <li class = "button">
                <%= link_to('Login', new_user_session_path) %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>
<!-- /Navbar -->

<!--<div class = "index-container"> -->
  <%= yield %>
<!--</div>-->

</body>
</html>

Prelude_v2/app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <!-- Add two fields for mp3 and chart -->
  <div class="field">
    <%= f.label :chart %>
    <h6>
      <%= f.file_field :chart %>
    </h6>
  </div>
  <div class="field">
    <%= f.label :mp3 %>
    <h6>
      <%= f.file_field :mp3 %>
    </h6>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Prelude_v2/app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

Prelude_v2/app/views/songs/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>
    <%= @current_user.band.name %>
    <%= link_to 'Add Song', new_song_path, class:"btn btn-sm btn-default" %>
  </h1>
</div>

<!-- Song table -->
<div  class = "song-table" style = "background-color: white;">
  <div class="container">
    <table class="table" id = "modified-table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Artist</th>
          <th>Chart</th>
          <th>MP3</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @songs.each do |song| %>
          <tr>
            <td><%= link_to song.name, song %></td>
            <td><%= link_to song.artist, song %></td>
            <td><%= link_to "Download", song.chart_url %></td>
            <td><%= link_to "Download", song.mp3_url %></td>
            <!--<td><%= link_to 'Show', song %></td>
            <td><%= link_to 'Edit', edit_song_path(song) %></td>
            <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
</div>

Prelude_v2/app/views/songs/new.html.erb
<div class="border-form-div">
  <h1>New Song</h1>

  <%= render 'form' %>

  <%= link_to 'Back', songs_path %>
</div>

Prelude_v2/app/views/songs/show.html.erb
<script>
  $(document).ready(function(){

    $("#jPlayer-player").jPlayer({
      ready: function (event) {
        $(this).jPlayer("setMedia", {
          title: "Bubble",
          mp3: "http://jplayer.org/audio/m4a/Miaow-07-Bubble.m4a",
          oga: "http://jplayer.org/audio/ogg/Miaow-07-Bubble.ogg"
        });
      },
      swfPath: "javascript",
      supplied: "mp3, oga",
      wmode: "window",
      useStateClassSkin: true,
      autoBlur: false,
      smoothPlayBar: true,
      keyEnabled: true,
      remainingDuration: true,
      toggleDuration: true
    });

  });
  </script>


  <!-- Band Name -->
  <div class = "container" >
    <h1>
      <%= @song.name %>
      By <%= @song.artist %>
    </h1>
  </div>



  <div class = "index-container">
    <div class = "container">
      <p id="notice"><%= notice %></p>


      <div id="jPlayer-player" class="jp-jplayer"></div>
        <div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
          <div class="jp-type-single">
            <div class="jp-gui jp-interface">
              <div class="jp-controls">
                <button class="jp-play" role="button" tabindex="0">play</button>
                <button class="jp-stop" role="button" tabindex="0">stop</button>
              </div>
              <div class="jp-progress">
                <div class="jp-seek-bar">
                  <div class="jp-play-bar"></div>
                </div>
              </div>
              <div class="jp-volume-controls">
                <button class="jp-mute" role="button" tabindex="0">mute</button>
                <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                <div class="jp-volume-bar">
                  <div class="jp-volume-bar-value"></div>
                </div>
              </div>
              <div class="jp-time-holder">
                <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                <div class="jp-toggles">
                  <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                </div>
              </div>
            </div>
            <div class="jp-no-solution">
              <span>Update Required</span>
              To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
            </div>
          </div>
        </div>

      <p>
        <strong>Download Chart:</strong>
        <% if @song.chart.file %>
          <%= link_to @song.chart.file.filename, @song.chart_url %>
        <% else %>
          No Chart Uploaded
        <% end %>
      </p>

      <p>
        <strong>Download MP3:</strong>
        <% if @song.mp3.file %>
          <%= link_to @song.mp3.file.filename, @song.mp3_url %>
        <% else %>
          No MP3 Uploaded
        <% end %>
      </p>

      <%= link_to 'Edit', edit_song_path(@song.id) %> |
      <%= link_to 'Back', songs_path %>
    </div>
  </div>